remote_theme: daattali/beautiful-jekyll@5.0.0

title: Github Pages - Daniel Tsivkovski

author: Daniel Tsivkovski

# --- List of links in the navigation bar --- #

navbar-links:
  Home: "/"
  Data Structures Project: "https://dtsivkovski.github.io/dtsivkovski-cspt3/dsProject"
  Test Prep / Notes: "https://dtsivkovski.github.io/dtsivkovski-cspt3/testPrep"
  Create Task: "https://dtsivkovski.github.io/dtsivkovski-cspt3/createtask"
  
github: dtsivkovski
  
# avatar: "https://avatars.githubusercontent.com/u/89223402?v=4"

# round-avatar: true

# Colors
navbar-col: "#087E8B"
navbar-text-col: "#3C3C3C"
navbar-border-col: "#087E8B"
page-col: "#3C3C3C"
text-col: "#F5F5F5"
link-col: "#087E8B"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
