remote_theme: daattali/beautiful-jekyll@5.0.0

title: Github Pages - Daniel Tsivkovski

author: Daniel Tsivkovski

# --- List of links in the navigation bar --- #

navbar-links:
  Home: "/"
  Data Structures Project: "https://dtsivkovski.github.io/dtsivkovski-cspt3/dsProject"
  Test Prep / Notes: "https://dtsivkovski.github.io/dtsivkovski-cspt3/testPrep"
  Create Task: "https://dtsivkovski.github.io/dtsivkovski-cspt3/createtask"
  
social-network-links:
  github: dtsivkovski
  
# avatar: "https://avatars.githubusercontent.com/u/89223402?v=4"

# round-avatar: true

